backend:
  name: git-gateway
  branch: main

media_folder: "static/img/uploads" # Where uploaded files will go in the repo
public_folder: "/img/uploads"       # How the site will refer to them

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
